services:
  # nginx:
  #   image: nginx:stable
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - user-service
  #     - search
  #   restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5005:5005"
    # environment:
    #   - API_GATEWAY=http://nginx
    # depends_on:
    #   - user-service
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./frontend:/app
    command: gunicorn -k gevent -w 1 -b 0.0.0.0:5005 app:app --timeout 100
    restart: unless-stopped

  # user-service:
  #   build: ./user-service
  #   volumes:
  #     - ./db/users:/data   # SQLite file lives here
  #   expose:
  #     - "8001"
  #   restart: unless-stopped

  # transcriber-template:
  #   build: ./transcriber-service
  #   volumes:
  #     - ./db/transcribers/template:/data  # template path; override per-user in real deploy
  #   expose:
  #     - "8002"
  transcriber-service:
    build:
      context: ./transcriber
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - ./transcriber:/app
    ports:
      - "8002:8002"
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:8002 app:app --timeout 100
    restart: unless-stopped

  # search:
  #   build: ./search
  #   depends_on:
  #     - user-service
  #     - transcriber
  #   restart: unless-stopped
  database:
    build: ./database
    ports:
      - "8004:8004"
    volumes:
      - ./db_data:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: "gunicorn -k gevent -w 1 -b 0.0.0.0:8004 'app:create_app()'"
    restart: unless-stopped