services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:   sttuser
      POSTGRES_PASSWORD: sttpass
      POSTGRES_DB:     stt
    volumes:
      - db_data:/var/lib/postgresql/data

  transcriber:
    build: ./transcriber
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://sttuser:sttpass@db:5432/stt

  search:
    build: ./search
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://sttuser:sttpass@db:5432/stt

  frontend:
    build: ./frontend
    depends_on: [transcriber, search]
    environment:
      API_URL: http://nginx

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on: [frontend, transcriber, search]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
